# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-06-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190627_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
